### ISSUE TITLE
Use docker_image module instead of `docker pull`

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1016]
Ansible [has a core module for dealing with docker images](http://docs.ansible.com/ansible/docker_image_module.html). It should be faster and less error prone to use this module, rather than the command module with `docker pull` as we do in several of our roles (at first glance: calico, haproxy, mantlui, marathon, and mesos).  

Transforming these is easy:
```yaml
- name: ensure {{ component }} docker image is present
  sudo: yes
  command: /usr/bin/docker pull {{ image }}:{{ image_tag }}
  tags:
    - bootstrap
```
becomes
```yaml
- name: ensure {{ component }} docker image is present
  become: yes
  docker_image:
    name: "{{ image }}"
    tag: "{{ image_tag }}"
    state: present
  tags: 
    - bootstrap
```
