### ISSUE TITLE
kubernetes should use the same certs as everything else

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1608]
No reason not to, and it'll reduce attack surface, complexity, and code.  

Looks like the certs were valid for the following SAN (from `roles/kubernetes/files/make-ca-cert.sh`):
```
dns_domain="${DNS_DOMAIN:="cluster.local"}"
sans="IP:${service_ip},IP:127.0.0.1,DNS:localhost,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.${dns_domain}"
```
That script is called with the following environment:
```yml
  environment:
    MASTERS: "kubernetes.service.consul"
    DNS_DOMAIN: "{{ dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"
    CERT_DIR: "{{ playbook_dir }}/{{ cert_syncdir.path }}/certs"
```
so the SAN will really include:
```
DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.service,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes.service.consul,DNS:kubernetes.default.src.{{ cluster_name or dns_domain }}
```
I don't think we need to have our certs valid for all those names though. Can anyone think of a reason to? 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0
