### ISSUE TITLE
Validate JSON templates with `jq`

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1624]
We use a lot of JSON templates throughout Mantl, and we should take advantage of Ansible's `validate` field to ensure that at provisioning time, they come out right. Here's a (possibly incomplete) list of candidates:
```
mantl ➤ ag -g '.*.json.j2'
roles/consul/templates/acl.json.j2
roles/consul/templates/agent_acl.json.j2
roles/consul/templates/consul.json.j2
roles/docker/templates/config.json.j2
roles/marathon/templates/mesos-consul.json.j2
roles/marathon/templates/mantl-api.json.j2
roles/zookeeper/templates/zk-consul.json.j2
roles/chronos/templates/chronos.json.j2
roles/glusterfs/templates/glusterfs-mounts.json.j2
roles/glusterfs/templates/glusterfs-volumes.json.j2
roles/glusterfs/templates/glusterfs.json.j2
roles/distributive/templates/consul-healthcheck.json.j2
roles/kafka/templates/kafka-manager.json.j2
roles/kafka/templates/kafka.json.j2
roles/kubernetes-node/templates/nodeport.json.j2
roles/elasticsearch/templates/elasticsearch-client.json.j2
roles/elasticsearch/templates/elasticsearch.json.j2
roles/kibana/templates/kibana-mesos.json.j2
roles/kibana/templates/kibana.json.j2
```
For example, this is the Consul configuration task before this change:
```yaml
- name: configure consul
  sudo: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/consul/{{ item }}
    owner: consul
    group: consul
  with_items:
    - consul.json
    - acl.json
  notify:
    - restart consul
  tags:
    - consul
```
and this is what it would look like afterwards
```
- name: configure consul
  sudo: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/consul/{{ item }}
    owner: consul
    group: consul
    validate: jq '' %s
  with_items:
    - consul.json
    - acl.json
  notify:
    - restart consul
  tags:
    - consul
```

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0
