### ISSUE TITLE
Pods no longer receive a valid ca.crt after #1753 merge

### ISSUE THREAD

**Issue by Dacode45** [CiscoCloud/mantl#1774]
After #1753

Hey guys, I'm not really sure how, but pods no longer seem to be getting a working certificate. 
All pods should get certs from `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` I've been trying to deploy an ingress controller with 
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      nodeSelector:
        role: edge
      volumes:
        - name: config-volume
          configMap:
            name: traefik-ingress-controller-config
      containers:
        - image: traefik
          name: traefik-ingress-lb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
          args:
            - -c
            - /etc/traefik/traefik.toml
            - --web
            - --logLevel=DEBUG
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-controller-config
data:
  traefik.toml: |-
    port = ":80"
    graceTimeOut = 10
    logLevel = "DEBUG"

    [web]
    address = ":8080"
    CertFile = "/etc/pki/mantl/cert"
    KeyFile = "/etc/pki/mantl/key"

    [marathon]
    endpoint = "http://marathon.service.consul:18080"
    domain = "marathon.localhost"
    watch = true
    networkInterface = "eth0"
    ExposedByDefault = true
# Traefik will use env variable KUBERNETES_SERVICE_HOST
# and KUBERNETES_SERVICE_PORT_HTTPS as endpoint
# Secure token will be found in /var/run/secrets/kubernetes.io/serviceaccount/token
# and SSL CA cert in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    [kubernetes]
```
Which worked yesterday. Now when I run it, traefik complains 
```
level=error msg="Error watching kubernetes events: failed to create watch: failed to do
 version request: GET \"https://10.254.0.1:443/apis/extensions/v1beta1/ingresses\" : http error 401 GET \"https://1
0.254.0.1:443/apis/extensions/v1beta1/ingresses\": \"Unauthorized\\n\"" 
```
