### ISSUE TITLE
failed to deploy consul in 1.2.0

### ISSUE THREAD

**Issue by yangzhares** [CiscoCloud/mantl#1795]
hi, 

when deploy consul in 1.2.0, faced an issue which failed to deploy nginx template task in `roles/consul/tasks/nginx_proxy.yml`, error info is directory `/etc/nginx/templates` doesn't exist. here is my patch which will create directory `/etc/nginx/templates` if doesn't exist before executing task `deploy nginx template`  to fix that issue.

```
- name: create nginx template direcotry if does not exist
  sudo: yes
  file:
    path: /etc/nginx/templates
    state: directory
    mode: 0700
  tags:
    - consul
```
