### ISSUE TITLE
Cleanup: remove wait for mesos-consul and mesos-api images in marathon role? 

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/mantl#932]
In `roles/marathon/tasks/jobs.yml`, we pull two docker containers onto every control node. Since those containers run on the workers, they are never used again. 

The good thing this task does is makes sure that images are present. But it does introduce some latency in the build. 

```
- name: ensure job docker images are present
  sudo: yes
  command: /usr/bin/docker pull {{ item }}
  with_items:
    - "{{ mesos_consul_image }}:{{ mesos_consul_image_tag }}"
    - "{{ mantl_api_image }}:{{ mantl_api_image_tag }}"
  tags:
    - marathon
    - bootstrap
```
